import type { Logger } from 'winston';
import type { JWTPayload } from '../shared/types';

declare global {
  namespace Express {
    interface Request {
      /** Correlation id generated by `requestIdMiddleware`. */
      requestId?: string;
      /** Request-scoped logger already stamped with `requestId`. */
      log?: Logger;
      /** Populated by `authenticate` / `optionalAuth`. */
      user?: JWTPayload;
    }
  }
}

export {};
